name: GitHub Actions Demo

on:
  push:
  #workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ secrets.MY }} event."
      - run: echo "The job was automatically triggered by a ${{ vars.MY_NAME }} event."
